<?php
  require_once "view/header.php";
?>
<!--hero-->
<section id="page-header" style="background-image: url('./assets/images/about/banner.png');">
  <h2>THÔNG TIN VÀ ĐIỀU KHOẢN</h2>
  <p>Thông tin và điều khoản của chúng tôi!</p>
</section>
<section id="about-head" class="section-p1">
  <div>
    <p>Các điều khoản và điều kiện sau đây (còn gọi là "Điều khoản") quản lý: (i) việc sử dụng của bạn trên BusyBees.com (hoặc bất kỳ các phụ trang nào của nó), hoặc một trong những trang web khác của chúng tôi, ứng dụng hoặc các dịch vụ khác mà bạn truy cập Điều khoản này (mỗi cái được gọi là một "Trang,"), và tổng hợp, các "Trang,"); và (ii) bất kỳ mua sắm nào bạn thực hiện từ Trang. Trong các Điều khoản này, “Công ty,” “chúng tôi” hoặc “chúng ta” có nghĩa là Gianni BusyBees S.r.l., cùng với các công ty mẹ, chi nhánh và các đơn vị liên kết của nó trên toàn thế giới. Bên hợp đồng của bạn cho việc mua bán hàng hóa qua BusyBees.com là GLOBAL-E NL B.V (“Global-E”). Bên hợp đồng của bạn cho việc sử dụng Trang web là nhà điều hành Trang web là Gianni BusyBees S.r.l. Trừ khi bị hạn chế bởi luật pháp áp dụng, các Điều khoản này có thể thay đổi từ thời gian này sang thời gian khác, vì vậy vui lòng xem xét chúng mỗi lần trước khi chấp nhận chúng và thực hiện mua sắm. Bằng cách đặt hàng cho bất kỳ sản phẩm nào hoặc truy cập hoặc sử dụng Trang và nhấp để đồng ý với các Điều khoản này trên Trang, hoặc bằng cách hoàn thành quy trình giao dịch đặt hàng cụ thể trên một Trang, bạn chấp nhận và đồng ý bị ràng buộc bởi các Điều khoản này. Nếu bạn không đồng ý với các Điều khoản này, bạn sẽ không thể mua bất kỳ sản phẩm nào thông qua các Trang và bạn không được phép truy cập hoặc sử dụng các Trang.</p>
    <b>1. THÔNG TIN VỀ CHÚNG TÔI</b>
    <p>Trang web này được điều hành bởi Gianni BusyBees S.r.l., một công ty được tổ chức và tồn tại dưới luật pháp của Ý, có trụ sở tại Piazza Luigi Einaudi 4, 20124 Milan, Italy, Mã số thuế và Đăng ký VAT số 04636090963, Số chỉ số Kinh tế và Hành chính số 1762567. GLOBAL-E NL B.V. là một công ty được đăng ký tại Hà Lan với số đăng ký 72541466 có trụ sở tại Krijn Taconiskade 430 1087 HW Amsterdam, Hà Lan. Global-E là đối tác hỗ trợ và thực hiện bán hàng quốc tế của chúng tôi và sẽ là công ty mà bạn ký hợp đồng để mua bất kỳ sản phẩm hoặc dịch vụ nào. Global-E sẽ tiến hành thanh toán của bạn và các nhà vận chuyển được phê duyệt sẽ giao hàng cho đơn hàng của bạn. Để biết thông tin chi tiết về chính sách hoàn trả và hoàn tiền của chúng tôi, vui lòng xem Mục 14 Quy định Hủy đơn hàng / Quyền Rút lui / Trả lại Đơn hàng. Các điểm đến mà chúng tôi hiện đang gửi hàng mua trên BusyBees.com bao gồm: Brazil, Colombia, Ấn Độ, Mexico, Peru, Ả Rập Saudi, Nam Phi, Thổ Nhĩ Kỳ, Các Tiểu Vương quốc Ả Rập Thống nhất, Việt Nam. Danh sách này có thể được cập nhật từ thời gian này sang thời gian khác.</p>
    <b>2. CÁC QUYỀN SỞ HỮU CỦA CHÚNG TÔI</b>
    <p>Trừ những Tài liệu đã Gửi của bạn (như được định nghĩa trong Phần 6 dưới đây), chúng tôi và/hoặc các bên cấp phép của chúng tôi sở hữu, duy nhất và độc quyền, tất cả các quyền, tiêu đề và quyền lợi (bao gồm, nhưng không giới hạn, quyền tác giả) đối với các Trang web, toàn bộ nội dung (bao gồm, nhưng không giới hạn, tất cả âm thanh, hình ảnh, minh họa, hình minh họa, vẽ, Phát sóng trực tuyến, Cấp nguồn thông tin RSS, podcast, dịch vụ khác, đồ họa, biểu trưng, trò chơi, tiện ích, các ứng dụng phân phối khác, các ứng dụng phát triển khác, hình ảnh khác, video, bản sao và phần mềm), mã, dữ liệu và các tài liệu khác trên đó (tổng hợp, "Nội dung Trang web"), vẻ ngoài, thiết kế và tổ chức của Trang web, và việc biên soạn và tổ chức của Nội dung Trang web, bao gồm nhưng không giới hạn đến bất kỳ quyền tác giả, quyền của tác giả, quyền thương hiệu, quyền sáng chế, quyền cơ sở dữ liệu, quyền đạo đức, quyền đặc biệt và các quyền sở hữu trí tuệ và tài sản khác trong đó. Việc sử dụng của bạn đối với Trang web không gây quyền sở hữu hay tiêu đề đối với bất kỳ Nội dung Trang web nào hoặc bất kỳ phần nào khác của Trang web, cũng như nó không cấp cho bạn bất kỳ giấy phép nào để sử dụng hoặc hiển thị như đã được phép một cách rõ ràng trong đây.</p>
    <b>3. "GIẤY PHÉP HẠN CHẾ</b>
    <p>Dưới sự tuân thủ đầy đủ các Điều khoản này, chúng tôi cấp cho bạn một giấy phép hạn chế, không độc quyền, không chuyển nhượng, không cho phép chuyển giao, để truy cập, xem, sử dụng và hiển thị các Trang web và Nội dung Trang web trên máy tính hoặc các thiết bị khác của bạn, miễn là bạn tuân thủ đầy đủ các Điều khoản này. Các Trang web và Nội dung Trang web chỉ dành cho việc sử dụng cá nhân, giáo dục và không thương mại của bạn. Không một phần nào của các Trang web hoặc Nội dung Trang web (hoặc bất kỳ sản phẩm nào được quảng cáo hoặc bán trên Trang web) có thể được sao chép, tái sản xuất, tái xuất bản, khai thác, tải xuống, tải lên, đăng, truyền, chỉnh sửa, phát sinh, chuyển đổi, phân tích ngược, khai thác, phân phối hoặc sử dụng bằng bất kỳ cách nào mà không có sự đồng ý bằng văn bản trước của chúng tôi hoặc của chủ sở hữu quyền lợi tương ứng, trừ trường hợp được phép sử dụng giới hạn cho các mục đích cá nhân, không thương mại hoặc giáo dục và bất kỳ giới hạn khác được phép theo luật pháp áp dụng.</p>
    <b>4. BẢN QUYỀN VÀ THƯƠNG HIỆU</b>
    <p>4.1.Tất cả nội dung trên trang web www.BusyBees.com bao gồm cả thương hiệu đã đăng ký và chưa đăng ký, logo, bản quyền, hình ảnh doanh nghiệp, tác phẩm, hình ảnh, ảnh, hội thoại, âm nhạc, âm thanh, video, tài liệu, thiết kế, hình ảnh, biểu tượng, menu, trang web, đồ họa, màu sắc, mẫu mã, công cụ, ký tự in, bản vẽ, biểu đồ, bố cục, phương pháp, quy trình, tính năng và phần mềm (tổng hợp, “Nội dung”), là tài sản của và/hoặc độc quyền sẵn có cho BusyBees và các nhà cung cấp nội dung của nó, và được bảo vệ bởi luật bản quyền Ý và các luật sở hữu trí tuệ khác.</p>
    <p>4.2.Người tiêu dùng không được sao chép, xuất bản, phân phối, xem, sửa đổi, tạo ra các tác phẩm từ hoặc hưởng lợi bằng bất kỳ cách nào, toàn bộ hoặc một phần, từ Nội dung, mà không có sự đồng ý trước bằng văn bản của BusyBees hoặc các nhà cung cấp nội dung của nó, tùy theo trường hợp, trừ khi, tuy nhiên, với tài liệu này, BusyBees cung cấp sự cho phép cho bạn xem, tải xuống và in các trang của trang web trong bản cứng, chỉ cho mục đích cá nhân và không dùng cho mục đích thương mại.</p>
    <p>4.3.BusyBees có quyền khẳng định sở hữu của mình đối với bất kỳ Nội dung nào được xuất bản trên Trang web, vào bất kỳ thời điểm nào, và phản đối bất kỳ việc sử dụng, biến t distort hoặc sửa đổi bất kỳ Nội dung đó cho bất kỳ mục đích nào.</p>
    <b>5. TÀI KHOẢN NGƯỜI DÙNG</b>
    <p>Sử dụng một số tính năng trên trang web có thể đòi hỏi tạo tài khoản và cung cấp thông tin cá nhân. Các chính sách về việc thu thập và sử dụng thông tin trên trang web được quy định trong Chính sách Bảo mật và Chính sách Cookie của chúng tôi. Bạn đồng ý chỉ cung cấp thông tin chính xác, hiện tại và đầy đủ. Bạn chịu trách nhiệm bảo mật thông tin tài khoản của mình (bao gồm mật khẩu), và bạn chấp nhận mọi trách nhiệm cho bất kỳ thông tin và hoạt động nào diễn ra dưới tài khoản của bạn. Chúng tôi có quyền tạm ngừng hoặc chấm dứt tài khoản của bạn nếu chúng tôi có lý do tin rằng bạn đã vi phạm các điều khoản này hoặc hạn chế quyền truy cập của bạn vào toàn bộ hoặc một phần của trang web theo phần Truy cập vào các trang web.</p>
  </div>
</section>
<?php
  require_once "view/footer.php";
?>